[colors.bright]
black = "#545454"
blue = "#94bff3"
cyan = "#93e0e3"
green = "#8ae234"
magenta = "#b294bb"
red = "#fc5454"
white = "#ffffff"
yellow = "#fce94f"

[colors.normal]
black = "#3f3f3f"
blue = "#94bff3"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#85678f"
red = "#cc0000"
white = "#dcdccc"
yellow = "#c4a000"

[colors.primary]
background = "#222222"
foreground = "#FFFFFF"     # previous  "#F9F9F9" "#FCFCFC"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[terminal.shell]
program = "/bin/zsh"

[terminal]
osc52 = "CopyPaste"

[window]
dynamic_padding = false
opacity = 0.8
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 4

[env]
LIBGL_ALWAYS_SOFTWARE = "1"
